# GENERATED by scripts/gen_models.sh from spec/openapi.yaml — do not hand-edit.

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Asset(BaseModel):
    """
    A user-owned record identified by a server-assigned UUID, backing an immutable blob whose content carries a server-computed blake3 hash. `hash` may be computed lazily: an asset record (and its retrievable bytes) can exist before its hash is filled in.
    """

    id: Annotated[str, Field(examples=['9f8a1c0d-2b3e-4f56-8a7b-1c2d3e4f5a6b'])]
    hash: Annotated[
        str | None,
        Field(
            description='`blake3:<hex>`; null while lazily computed.',
            examples=['blake3:9f8a1c0d...'],
        ),
    ]
    size_bytes: Annotated[int, Field(examples=[4816293])]
    content_type: Annotated[str, Field(examples=['image/png'])]
    file_path: Annotated[str | None, Field(examples=['photo.png'])] = None
    created_new: Annotated[
        bool | None,
        Field(
            description='On create responses: distinguishes a brand-new blob (true) from a dedup hit against bytes the platform already had (false).'
        ),
    ] = None
    created_at: AwareDatetime
    url: Annotated[
        AnyUrl, Field(description='Short-lived content URL (signed, or proxy-served).')
    ]
    url_expires_at: AwareDatetime
    expires_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Retention deadline for the asset itself (distinct from `url_expires_at`, the signed URL's validity). Null or absent means the asset is non-expiring. On a dedup-hit create response the deadline may be later than now + the requested/default retention: re-referencing content extends its retention, never shortens it."
        ),
    ] = None
    job_id: Annotated[
        str | None,
        Field(
            description='ID of the job that produced this asset. Absent for uploaded assets, which have no producing job.'
        ),
    ] = None


class Format(Enum):
    """
    Discriminates the `workflow` field's shape. `save`: the original authoring workflow JSON, at the version pinned to the job. `api`: the executed API-format prompt graph.
    """

    save = 'save'
    api = 'api'


class JobWorkflowResponse(BaseModel):
    """
    The workflow behind a job. See GET /api/v2/jobs/{id}/workflow's description for exactly when `format` is `save` vs `api`.
    """

    workflow: Annotated[
        dict[str, Any],
        Field(description='The workflow, verbatim, in the shape `format` says.'),
    ]
    format: Annotated[
        Format,
        Field(
            description="Discriminates the `workflow` field's shape. `save`: the original authoring workflow JSON, at the version pinned to the job. `api`: the executed API-format prompt graph."
        ),
    ]


class JobStatus(Enum):
    """
    Lifecycle: queued → running → succeeded | failed | expired;
    a cancel request moves running → canceling → canceled.
    Terminal states: succeeded, canceled, failed, expired.

    """

    queued = 'queued'
    running = 'running'
    succeeded = 'succeeded'
    canceling = 'canceling'
    canceled = 'canceled'
    failed = 'failed'
    expired = 'expired'


class JobUrls(BaseModel):
    """
    Embedded follow-up links — follow these, don't build URLs. A link is either an absolute URL or a host-relative reference (leading `/`) that already includes any prefix the serving surface is mounted under (e.g. a serverless gateway's `/deployment/{deployment_id}/api/v2`). Clients MUST resolve a host-relative link against the request origin (scheme + authority), never against a configured base URL — joining it to a base URL that carries the same mount prefix duplicates the prefix.
    """

    self: str
    events: str
    cancel: str


class Progress(BaseModel):
    """
    Server-computed progress snapshot (node-count and sampler-step weighted). Complete per snapshot — one fully re-syncs a client.
    """

    value: Annotated[
        float,
        Field(
            description='Overall fraction, server-computed.',
            examples=[0.42],
            ge=0.0,
            le=1.0,
        ),
    ]
    nodes_done: Annotated[int, Field(examples=[11])]
    nodes_total: Annotated[int, Field(examples=[31])]
    current_node: Annotated[str | None, Field(examples=['12'])] = None
    current_node_class: Annotated[str | None, Field(examples=['KSampler'])] = None
    step: Annotated[int | None, Field(examples=[21])] = None
    steps: Annotated[int | None, Field(examples=[50])] = None
    message: Annotated[str | None, Field(examples=['KSampler 21/50'])] = None


class OutputType(Enum):
    """
    Normalized output kind — nothing silently dropped.
    """

    image = 'image'
    video = 'video'
    audio = 'audio'
    text = 'text'
    file = 'file'
    latent = 'latent'


class JobError(BaseModel):
    """
    Execution failure detail, carried in `job.error` (not an HTTP error).
    """

    code: Annotated[str, Field(examples=['node_execution_error'])]
    message: str
    node_id: str | None = None
    class_type: str | None = None
    traceback: str | None = None


class Error(BaseModel):
    code: Annotated[str, Field(examples=['invalid_workflow'])]
    message: Annotated[
        str,
        Field(examples=["Node 12 (KSampler): required input 'model' is not connected"]),
    ]
    details: Annotated[
        dict[str, Any] | None,
        Field(
            examples=[
                {'node_errors': {'12': [{'field': 'model', 'reason': 'missing_input'}]}}
            ]
        ),
    ] = None


class ErrorEnvelope(BaseModel):
    """
    Shared error envelope with machine-readable codes. Core codes (v1):
    `invalid_workflow` (422), `workflow_format_ui` (422),
    `missing_asset` (422), `hash_mismatch` (409), `blob_not_found`
    (404), `idempotency_key_reuse` (422),
    `queue_full` (429 + Retry-After), `insufficient_credits` (402),
    `not_found` (404), `unauthorized` (401), `forbidden` (403).
    Deployment-scoped surfaces add: `deployment_not_ready` (429 +
    Retry-After — the deployment can still reach ready; retry) and
    `deployment_stopped` (422 — terminal deployment state; a retry
    cannot succeed without operator action). A 429 is disambiguated
    by `error.code` alone; clients should treat any 429 + Retry-After
    as "back off and retry".

    """

    error: Error


class StatusEvent(BaseModel):
    """
    SSE `status` event payload.
    """

    status: JobStatus
    queue_position: int | None = None


class PreviewEvent(BaseModel):
    """
    SSE `preview` event payload (JPEG, base64, throttled).
    """

    node_id: str
    content_type: Annotated[str, Field(examples=['image/jpeg'])]
    data_base64: str


class LogEvent(BaseModel):
    """
    SSE `log` event payload. Best-effort diagnostics.
    """

    level: Annotated[str, Field(examples=['info'])]
    message: str


class FieldType(Enum):
    core_ASSET = 'core/ASSET'


class Info(BaseModel):
    id: Annotated[str, Field(examples=['9f8a1c0d-2b3e-4f56-8a7b-1c2d3e4f5a6b'])]
    hash: Annotated[str | None, Field(examples=['blake3:9f8a1c0d...'])] = None
    file_path: Annotated[str | None, Field(examples=['photo.png'])] = None


class AssetReference(BaseModel):
    """
    The typed asset-reference object placed inside workflow JSON where a
    filename would normally go (documented here for tooling; it is not a
    request/response body itself):

        {"__type": "core/ASSET",
         "info": {"id": "<asset-uuid>", "hash": "blake3:...",
                  "file_path": "photo.png"}}

    `info.id` (the asset UUID) is required in v1 and authoritative;
    `hash` and `file_path` are optional staging/lookup hints and never
    override a present `id`. A malformed reference or one that is not
    resolvable/owned by the caller fails submission with 422
    `missing_asset`.

    """

    field__type: Annotated[FieldType, Field(alias='__type')]
    info: Info


class Output(BaseModel):
    """
    A committed job output. Outputs are assets: `id` is the asset UUID, retrievable via GET /api/v2/assets/{id} for as long as the job is retained. `hash` is lazily computed and may be null on the retrieval hot path.
    """

    node_id: Annotated[str, Field(examples=['9'])]
    name: Annotated[str, Field(examples=['ComfyUI_00001_.png'])]
    type: OutputType
    content_type: Annotated[str, Field(examples=['image/png'])]
    size_bytes: Annotated[int, Field(examples=[1848320])]
    id: Annotated[
        str, Field(description='Asset UUID.', examples=['9f8a1c0d-2b3e-4f56-...'])
    ]
    hash: Annotated[
        str | None, Field(description='`blake3:<hex>`; null until lazily computed.')
    ]
    url: AnyUrl
    url_expires_at: AwareDatetime
    job_id: Annotated[
        str | None, Field(description='ID of the job that produced this output.')
    ] = None


class Job(BaseModel):
    """
    One execution of a workflow. Durable from creation until `expires_at`; `outputs` populates incrementally during execution.
    """

    id: Annotated[str, Field(examples=['7f3d2c1b-9a8e-4d6f-b012-3c4d5e6f7a8b'])]
    status: JobStatus
    created_at: AwareDatetime
    started_at: Annotated[AwareDatetime | None, Field(...)]
    completed_at: Annotated[AwareDatetime | None, Field(...)]
    expires_at: Annotated[
        AwareDatetime,
        Field(
            description='Retention deadline — a platform property, not an API constant.'
        ),
    ]
    queue_position: Annotated[int | None, Field(...)]
    progress: Annotated[
        Progress | None,
        Field(
            description='The latest progress snapshot; same data the SSE stream pushes.'
        ),
    ]
    outputs: list[Output]
    error: Annotated[JobError | None, Field(...)]
    metrics: Annotated[
        dict[str, int | None] | None,
        Field(
            description='Values are nullable (a metric not yet available — e.g. `execution_ms` before a job starts running — is `null`, not omitted); the example below is deliberately all-non-null purely to work around a Spectral/nimma lint-tooling crash on a literal `null` inside a schema `example` combined with `additionalProperties.nullable: true` — the schema itself is unchanged and still allows null values at runtime.',
            examples=[{'queue_ms': 9000, 'execution_ms': 42000}],
        ),
    ] = None
    urls: JobUrls
