#!/usr/bin/env python3
"""Fail if the committed tree drifts from the vendored specs.

Three checks, one job:

1. **Models vs ``spec/openapi.yaml``.** Regenerates the models into a temp file
   and diffs against the committed one, so a spec edit without a regen (or a
   hand-edit of the generated file) is caught. Mirrors the codegen-freshness
   gate other repos enforce.
2. **Router exception classes vs ``spec/router-openapi.yaml``.** The router
   surface has no generated artifact -- its contract lands in the SDK as the
   hand-written class table in ``comfy_sdk.router_exceptions``. So the drift
   that matters there is a bucket the spec declares and the SDK has no class
   for, which would reach callers as an untyped ``RouterError``. This compares
   the spec's ``x-comfy-error-types`` list against ``ROUTER_ERROR_TYPES``,
   which is what makes the next vendored Router sync a real diff review.
3. **The bound model-run route vs ``spec/router-openapi.yaml``.** Same reason,
   different artifact: ``comfy_low.transport`` posts a model run to a
   hand-written path constant and a hand-written host constant. The spec
   declares both -- the path whose ``post.operationId`` is ``runRouterModel``,
   and ``servers[0].url``. A sync that *moves* the route (the ``/v1`` -> ``/v2``
   move already on the roadmap) while those constants stay put would leave the
   SDK posting to a route the contract no longer declares, with nothing else in
   CI noticing.

``tests/test_router_spec_contract.py`` asserts the same things from the test
suite. Both exist on purpose: the suite is where a contributor sees it, and
this script is the job that fails a spec-only PR that never ran pytest.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMITTED = ROOT / "src" / "comfy_low" / "models" / "_generated.py"
ROUTER_SPEC = ROOT / "spec" / "router-openapi.yaml"


def _generate(out: Path) -> None:
    subprocess.run(
        [
            "datamodel-codegen",
            "--input",
            str(ROOT / "spec" / "openapi.yaml"),
            "--input-file-type",
            "openapi",
            "--output",
            str(out),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.10",
            "--use-standard-collections",
            "--use-union-operator",
            "--use-schema-description",
            "--field-constraints",
            "--collapse-root-models",
            "--strict-nullable",
            "--use-annotated",
            "--disable-timestamp",
            "--custom-file-header",
            "# GENERATED by scripts/gen_models.sh from spec/openapi.yaml — do not hand-edit.",
        ],
        check=True,
    )


def _declared_router_error_types() -> list[str]:
    """The router spec's ``x-comfy-error-types`` values, in declaration order.

    Raises :class:`ValueError` rather than letting a ``KeyError``/``TypeError``
    escape: a sync that reshapes or drops the extension should fail this job
    with a sentence someone can act on, not with a traceback that reads like a
    bug in the checker. The likelier sync mistakes are turned into the same kind
    of sentence for the same reason -- an unparseable file (``yaml.YAMLError``),
    an unreadable one (``OSError``), and a checkout without the ``codegen``
    extra, where ``import yaml`` itself is what fails.

    ``encoding="utf-8"`` is explicit because the spec's ``meaning`` prose is not
    ASCII: reading it under a non-UTF-8 locale default -- the Windows case --
    would raise ``UnicodeDecodeError`` from a file that is perfectly fine.
    """
    try:
        import yaml
    except ImportError as exc:  # pragma: no cover - depends on the install extra
        raise ValueError(
            f"PyYAML is not installed, so {ROUTER_SPEC.name} cannot be read "
            "(pip install -e '.[dev]')"
        ) from exc

    try:
        doc = yaml.safe_load(ROUTER_SPEC.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ValueError(f"{ROUTER_SPEC.name} could not be read: {exc}") from exc
    except yaml.YAMLError as exc:
        raise ValueError(f"{ROUTER_SPEC.name} is not valid YAML: {exc}") from exc

    node: object = doc
    for key in ("components", "schemas", "RouterErrorType", "x-comfy-error-types"):
        if not isinstance(node, dict) or key not in node:
            raise ValueError(f"{ROUTER_SPEC.name} has no components.schemas.RouterErrorType.{key}")
        node = node[key]
    if not isinstance(node, list) or not node:
        raise ValueError(f"{ROUTER_SPEC.name}'s x-comfy-error-types is not a non-empty list")
    values: list[str] = []
    for entry in node:
        if not isinstance(entry, dict) or not isinstance(entry.get("value"), str):
            raise ValueError(f"{ROUTER_SPEC.name} has an x-comfy-error-types entry with no value")
        # Rejected here rather than downstream: `ROUTER_ERROR_TYPES` is built
        # from a dict and so is deduplicated, and a repeated value would make
        # the two lists differ only in length -- reported below as "same values,
        # different order", sending the operator hunting for an ordering diff
        # that does not exist.
        if entry["value"] in values:
            raise ValueError(
                f"{ROUTER_SPEC.name} declares x-comfy-error-types value "
                f"{entry['value']!r} more than once"
            )
        values.append(entry["value"])
    return values


def _declared_run_route() -> tuple[str, str]:
    """The spec's ``(runRouterModel path, servers[0].url)``.

    Same failure policy as :func:`_declared_router_error_types`: every way the
    file can be unusable becomes a ``ValueError`` with a sentence someone can
    act on, rather than a traceback that reads like a bug in the checker.
    """
    try:
        import yaml
    except ImportError as exc:  # pragma: no cover - depends on the install extra
        raise ValueError(
            f"PyYAML is not installed, so {ROUTER_SPEC.name} cannot be read "
            "(pip install -e '.[dev]')"
        ) from exc

    try:
        doc = yaml.safe_load(ROUTER_SPEC.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ValueError(f"{ROUTER_SPEC.name} could not be read: {exc}") from exc
    except yaml.YAMLError as exc:
        raise ValueError(f"{ROUTER_SPEC.name} is not valid YAML: {exc}") from exc

    if not isinstance(doc, dict):
        raise ValueError(f"{ROUTER_SPEC.name} is not a mapping at the top level")
    paths = doc.get("paths")
    if not isinstance(paths, dict):
        raise ValueError(f"{ROUTER_SPEC.name} has no paths object")
    # Searched by operationId rather than looked up by the path we expect: a
    # lookup would silently find nothing the day the path moves, which is the
    # one day this check exists for.
    declared = [
        path
        for path, item in paths.items()
        if isinstance(item, dict)
        and isinstance(item.get("post"), dict)
        and item["post"].get("operationId") == "runRouterModel"
    ]
    if len(declared) != 1:
        raise ValueError(
            f"{ROUTER_SPEC.name} declares {len(declared)} paths with "
            f"post.operationId 'runRouterModel' (expected exactly 1): {declared}"
        )
    servers = doc.get("servers")
    if not isinstance(servers, list) or not servers or not isinstance(servers[0], dict):
        raise ValueError(f"{ROUTER_SPEC.name} has no servers[0]")
    host = servers[0].get("url")
    if not isinstance(host, str) or not host:
        raise ValueError(f"{ROUTER_SPEC.name}'s servers[0].url is not a non-empty string")
    return declared[0], host


def _check_router_run_route() -> int:
    if not ROUTER_SPEC.exists():
        print(f"ERROR: {ROUTER_SPEC.name} is missing from spec/", file=sys.stderr)
        return 1
    sys.path.insert(0, str(ROOT / "src"))
    try:
        from comfy_low.transport import _MODEL_RUN_PATH_TEMPLATE, ROUTER_BASE_URL
    except Exception as exc:
        print(f"ERROR: comfy_low.transport does not import: {exc!r}", file=sys.stderr)
        return 1

    try:
        declared_path, declared_host = _declared_run_route()
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    failed = False
    if declared_path != _MODEL_RUN_PATH_TEMPLATE:
        print(
            f"ERROR: the bound model-run route has drifted from {ROUTER_SPEC.name}.\n"
            f"  spec (runRouterModel): {declared_path}\n"
            f"  sdk  (_MODEL_RUN_PATH_TEMPLATE): {_MODEL_RUN_PATH_TEMPLATE}\n"
            "  Update comfy_low.transport._MODEL_RUN_PATH_TEMPLATE to the spec's path.",
            file=sys.stderr,
        )
        failed = True
    if declared_host != ROUTER_BASE_URL:
        print(
            f"ERROR: the default router host has drifted from {ROUTER_SPEC.name}.\n"
            f"  spec (servers[0].url): {declared_host}\n"
            f"  sdk  (ROUTER_BASE_URL): {ROUTER_BASE_URL}\n"
            "  Update comfy_low.transport.ROUTER_BASE_URL to the spec's server URL.",
            file=sys.stderr,
        )
        failed = True
    if failed:
        return 1
    print(f"OK: the SDK posts a model run to {declared_host}{declared_path}, as the spec declares")
    return 0


def _check_models() -> int:
    if not COMMITTED.exists():
        print("ERROR: committed models missing; run scripts/gen_models.sh", file=sys.stderr)
        return 1
    with tempfile.TemporaryDirectory() as td:
        fresh = Path(td) / "_generated.py"
        _generate(fresh)
        if fresh.read_text() != COMMITTED.read_text():
            print(
                "ERROR: comfy_low models are stale.\n"
                "Run scripts/gen_models.sh and commit src/comfy_low/models/_generated.py.",
                file=sys.stderr,
            )
            return 1
    print("OK: comfy_low models are in sync with spec/openapi.yaml")
    return 0


def _check_router_error_types() -> int:
    if not ROUTER_SPEC.exists():
        print(f"ERROR: {ROUTER_SPEC.name} is missing from spec/", file=sys.stderr)
        return 1
    # Imported here rather than at module scope so the models check above still
    # runs (and still reports) when the package itself will not import.
    sys.path.insert(0, str(ROOT / "src"))
    try:
        from comfy_sdk.router_exceptions import ROUTER_ERROR_TYPES
    except Exception as exc:
        # This check supervises that very module, so a syntax or import error
        # in it is the failure to report, not a traceback to leak.
        print(f"ERROR: comfy_sdk.router_exceptions does not import: {exc!r}", file=sys.stderr)
        return 1

    try:
        declared = _declared_router_error_types()
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    known = list(ROUTER_ERROR_TYPES)
    if declared == known:
        print(
            f"OK: comfy_sdk.router_exceptions covers all {len(declared)} error types "
            "in spec/router-openapi.yaml"
        )
        return 0

    missing = [value for value in declared if value not in known]
    extra = [value for value in known if value not in declared]
    print(
        "ERROR: the router exception table has drifted from spec/router-openapi.yaml.",
        file=sys.stderr,
    )
    if missing:
        print(
            f"  declared in the spec, no class in the SDK: {', '.join(missing)}\n"
            "  Add one RouterError subclass per value to src/comfy_sdk/router_exceptions.py,\n"
            "  named as the PascalCase of the wire value, with the spec's `meaning`\n"
            "  as its docstring.",
            file=sys.stderr,
        )
    if extra:
        print(
            f"  a class in the SDK, not declared in the spec: {', '.join(extra)}",
            file=sys.stderr,
        )
    if not missing and not extra:
        print(
            f"  same values, different order.\n    spec: {declared}\n    sdk:  {known}",
            file=sys.stderr,
        )
    return 1


def _run(name: str, check: Callable[[], int]) -> int:
    """One check's exit code, with a raised exception counted as a failure.

    Without this a check that *raises* rather than returns takes the whole job
    down with it -- ``_check_models`` runs ``datamodel-codegen`` under
    ``check=True``, so a codegen failure is a ``CalledProcessError`` and a
    missing binary a ``FileNotFoundError``. Either would abort ``main`` before
    the router check ran, which is exactly the hiding both checks exist to
    prevent.
    """
    try:
        return check()
    except Exception as exc:
        print(f"ERROR: the {name} check failed to run: {exc!r}", file=sys.stderr)
        return 1


def main() -> int:
    # All three run every time: reporting only the first failure would hide the
    # others behind a fix for it. `max` over the results rather than a
    # short-circuit for the same reason.
    return max(
        _run("models", _check_models),
        _run("router error types", _check_router_error_types),
        _run("router run route", _check_router_run_route),
    )


if __name__ == "__main__":
    raise SystemExit(main())
